import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useParams } from "react-router-dom";
import { getProjectByIdRequest, updateProjectRequest } from "../api/projects";
import ProjectForm from "../components/ProjectForm";
import type { ProjectPayload } from "../types/project";

function getProjectId(value: string | undefined) {
  const parsedValue = Number(value);

  if (!Number.isInteger(parsedValue) || parsedValue <= 0) {
    return null;
  }

  return parsedValue;
}

export default function ProjectEditPage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { projectId: projectIdParam } = useParams();
  const projectId = getProjectId(projectIdParam);
  const projectQuery = useQuery({
    enabled: projectId !== null,
    queryFn: () => getProjectByIdRequest(projectId as number),
    queryKey: ["project", projectId],
  });

  const handleSubmit = async (payload: ProjectPayload) => {
    if (projectId === null) {
      return;
    }

    await updateProjectRequest(projectId, payload);
    await queryClient.invalidateQueries({ queryKey: ["projects"] });
    await queryClient.invalidateQueries({ queryKey: ["project", projectId] });
    navigate("/projects");
  };

  const initialDataError =
    projectId === null
      ? "ID da obra inválido."
      : projectQuery.isError
        ? "Não foi possível carregar os dados da obra."
        : null;

  const initialValues =
    projectQuery.data === undefined
      ? {
          code: "",
          name: "",
          projectTypeId: "",
          city: "",
          state: "",
          notes: "",
        }
      : {
          code: projectQuery.data.code,
          name: projectQuery.data.name,
          projectTypeId:
            projectQuery.data.projectTypeId === null
              ? ""
              : String(projectQuery.data.projectTypeId),
          city: projectQuery.data.city,
          state: projectQuery.data.state,
          notes: projectQuery.data.notes,
        };

  return (
    <ProjectForm
      initialDataError={initialDataError}
      initialValues={initialValues}
      isCodeAutoGenerated
      isInitialDataLoading={projectQuery.isLoading}
      onCancel={() => navigate("/projects")}
      onSubmit={handleSubmit}
      submitLabel="Salvar alterações"
      subtitle="Atualize os dados da obra e mantenha o cadastro consistente."
      title="Editar obra"
    />
  );
}
