import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import {
  createProjectRequest,
  getNextProjectCodeRequest,
} from "../api/projects";
import ProjectForm, { type ProjectFormValues } from "../components/ProjectForm";

const defaultProjectFormValues: ProjectFormValues = {
  code: "",
  name: "",
  projectTypeId: "",
  city: "",
  state: "",
  notes: "",
};

export default function ProjectCreatePage() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const nextCodeQuery = useQuery({
    queryFn: getNextProjectCodeRequest,
    queryKey: ["project-next-code"],
  });

  const handleSubmit = async (payload: {
    code: string;
    name: string;
    projectTypeId: number | null;
    city: string;
    state: string;
    notes: string;
  }) => {
    await createProjectRequest(payload);
    await queryClient.invalidateQueries({ queryKey: ["projects"] });
    navigate("/projects");
  };

  return (
    <ProjectForm
      initialDataError={
        nextCodeQuery.isError
          ? "Nao foi possivel gerar o codigo automatico da obra."
          : null
      }
      initialValues={{
        ...defaultProjectFormValues,
        code: nextCodeQuery.data ?? "",
      }}
      isCodeAutoGenerated
      isInitialDataLoading={nextCodeQuery.isLoading}
      onCancel={() => navigate("/projects")}
      onSubmit={handleSubmit}
      submitLabel="Salvar obra"
      subtitle="Cadastre uma nova obra com codigo gerado automaticamente para vinculo operacional e consultas futuras."
      title="Nova obra"
    />
  );
}
