import ArrowBackRoundedIcon from "@mui/icons-material/ArrowBackRounded";
import ContentCopyRoundedIcon from "@mui/icons-material/ContentCopyRounded";
import SaveRoundedIcon from "@mui/icons-material/SaveRounded";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Alert,
  Box,
  Button,
  IconButton,
  InputAdornment,
  MenuItem,
  TextField,
  Tooltip,
} from "@mui/material";
import { useQuery } from "@tanstack/react-query";
import { isAxiosError } from "axios";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { PageHeader } from "../../../components/common/PageHeader";
import { SectionCard } from "../../../components/common/SectionCard";
import { listProjectTypesRequest } from "../api/projects";
import type { ProjectPayload } from "../types/project";

const projectFormSchema = z.object({
  code: z.string().trim().max(50, "O codigo deve ter no maximo 50 caracteres"),
  name: z
    .string()
    .trim()
    .min(3, "Informe uma descricao com pelo menos 3 caracteres")
    .max(200, "A descricao deve ter no maximo 200 caracteres"),
  projectTypeId: z.string(),
  city: z
    .string()
    .trim()
    .max(100, "A cidade deve ter no maximo 100 caracteres"),
  state: z.string().trim().max(50, "O estado deve ter no maximo 50 caracteres"),
  notes: z.string().trim(),
});

export type ProjectFormValues = z.infer<typeof projectFormSchema>;

type ProjectFormProps = {
  initialDataError?: string | null;
  initialValues: ProjectFormValues;
  isCodeAutoGenerated?: boolean;
  isInitialDataLoading?: boolean;
  onCancel: () => void;
  onSubmit: (payload: ProjectPayload) => Promise<void>;
  submitLabel: string;
  subtitle: string;
  title: string;
};

function getSubmitErrorMessage(error: unknown) {
  if (isAxiosError<{ message?: string }>(error)) {
    return error.response?.data?.message ?? "Nao foi possivel salvar a obra.";
  }

  return "Nao foi possivel salvar a obra.";
}

function mapFormValuesToPayload(values: ProjectFormValues): ProjectPayload {
  const normalizedProjectTypeId = values.projectTypeId.trim();

  return {
    code: values.code.trim(),
    name: values.name.trim(),
    projectTypeId:
      normalizedProjectTypeId === "" ? null : Number(normalizedProjectTypeId),
    city: values.city.trim(),
    state: values.state.trim(),
    notes: values.notes.trim(),
  };
}

export default function ProjectForm({
  initialDataError = null,
  initialValues,
  isCodeAutoGenerated = false,
  isInitialDataLoading = false,
  onCancel,
  onSubmit,
  submitLabel,
  subtitle,
  title,
}: ProjectFormProps) {
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const projectTypesQuery = useQuery({
    queryKey: ["project-types"],
    queryFn: listProjectTypesRequest,
  });
  const {
    formState: { errors, isSubmitting },
    handleSubmit,
    register,
    watch,
  } = useForm<ProjectFormValues>({
    defaultValues: initialValues,
    resolver: zodResolver(projectFormSchema),
    values: initialValues,
  });
  const currentCode = watch("code").trim();

  const handleCopyCode = async () => {
    if (currentCode === "") {
      return;
    }

    try {
      await navigator.clipboard.writeText(currentCode);
      setSubmitError(null);
      setCopyFeedback("Codigo da obra copiado.");
    } catch {
      setCopyFeedback(null);
      setSubmitError("Nao foi possivel copiar o codigo da obra.");
    }
  };

  const handleFormSubmit = async (values: ProjectFormValues) => {
    try {
      setCopyFeedback(null);
      setSubmitError(null);
      await onSubmit(mapFormValuesToPayload(values));
    } catch (error) {
      setSubmitError(getSubmitErrorMessage(error));
    }
  };

  return (
    <Box component="form" onSubmit={handleSubmit(handleFormSubmit)}>
      <PageHeader
        action={
          <Button
            onClick={onCancel}
            startIcon={<ArrowBackRoundedIcon />}
            variant="outlined"
          >
            Voltar
          </Button>
        }
        description={subtitle}
        title={title}
      />

      <Box sx={{ mt: 3 }}>
        <SectionCard
          description="Cadastre a descricao da obra, com codigo gerado automaticamente e dados complementares para apoio operacional."
          title="Dados da obra"
        >
          {initialDataError ? (
            <Alert severity="error">{initialDataError}</Alert>
          ) : null}
          {copyFeedback ? (
            <Alert severity="success">{copyFeedback}</Alert>
          ) : null}
          {submitError ? <Alert severity="error">{submitError}</Alert> : null}
          {projectTypesQuery.isError ? (
            <Alert severity="warning" variant="outlined">
              Nao foi possivel carregar os tipos de obra. Voce ainda pode salvar
              a obra sem esse vinculo.
            </Alert>
          ) : null}

          <Box
            sx={{
              display: "grid",
              gap: 2,
              gridTemplateColumns: {
                md: "repeat(2, minmax(0, 1fr))",
                xs: "minmax(0, 1fr)",
              },
            }}
          >
            <TextField
              error={Boolean(errors.code)}
              fullWidth
              helperText={
                errors.code?.message ??
                (isCodeAutoGenerated
                  ? currentCode === ""
                    ? isInitialDataLoading
                      ? "Gerando codigo automatico da obra..."
                      : "O codigo sera gerado automaticamente ao salvar a obra."
                    : "Codigo gerado automaticamente pelo sistema."
                  : undefined)
              }
              label="Codigo"
              placeholder="Ex: OBR-000001"
              slotProps={{
                input: {
                  endAdornment:
                    currentCode === "" ? undefined : (
                      <InputAdornment position="end">
                        <Tooltip title="Copiar codigo">
                          <IconButton
                            aria-label="Copiar codigo"
                            edge="end"
                            onClick={handleCopyCode}
                            size="small"
                          >
                            <ContentCopyRoundedIcon fontSize="small" />
                          </IconButton>
                        </Tooltip>
                      </InputAdornment>
                    ),
                  readOnly: isCodeAutoGenerated,
                },
              }}
              {...register("code")}
            />
            <TextField
              error={Boolean(errors.name)}
              fullWidth
              helperText={errors.name?.message}
              label="Descricao"
              placeholder="Ex: Centro Empresarial Campinas"
              {...register("name")}
            />
            <TextField
              error={Boolean(errors.projectTypeId)}
              fullWidth
              helperText={errors.projectTypeId?.message}
              label="Tipo de obra"
              select
              {...register("projectTypeId")}
            >
              <MenuItem value="">Nao informado</MenuItem>
              {(projectTypesQuery.data ?? []).map((item) => (
                <MenuItem key={item.id} value={String(item.id)}>
                  {item.name}
                </MenuItem>
              ))}
            </TextField>
            <TextField
              error={Boolean(errors.city)}
              fullWidth
              helperText={errors.city?.message}
              label="Cidade"
              placeholder="Ex: Campinas"
              {...register("city")}
            />
            <TextField
              error={Boolean(errors.state)}
              fullWidth
              helperText={errors.state?.message}
              label="Estado"
              placeholder="Ex: SP"
              {...register("state")}
            />
            <TextField
              error={Boolean(errors.notes)}
              fullWidth
              helperText={errors.notes?.message}
              label="Observacoes"
              multiline
              minRows={4}
              sx={{ gridColumn: { md: "1 / -1", xs: "auto" } }}
              {...register("notes")}
            />
          </Box>

          <Box
            sx={{
              display: "flex",
              gap: 1.5,
              justifyContent: "flex-end",
              pt: 1,
            }}
          >
            <Button onClick={onCancel} variant="text">
              Cancelar
            </Button>
            <Button
              disabled={isSubmitting || isInitialDataLoading}
              startIcon={<SaveRoundedIcon />}
              type="submit"
              variant="contained"
            >
              {isSubmitting ? "Salvando..." : submitLabel}
            </Button>
          </Box>
        </SectionCard>
      </Box>
    </Box>
  );
}
