import ArrowBackRoundedIcon from "@mui/icons-material/ArrowBackRounded";
import ContentCopyRoundedIcon from "@mui/icons-material/ContentCopyRounded";
import SaveRoundedIcon from "@mui/icons-material/SaveRounded";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  Alert,
  Box,
  Button,
  CircularProgress,
  IconButton,
  InputAdornment,
  MenuItem,
  TextField,
  Tooltip,
  Typography,
} from "@mui/material";
import { alpha } from "@mui/material/styles";
import { useQuery } from "@tanstack/react-query";
import { isAxiosError } from "axios";
import type { ReactNode } from "react";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { PageHeader } from "../../../components/common/PageHeader";
import { SectionCard } from "../../../components/common/SectionCard";
import { listProjectTypesRequest } from "../api/projects";
import type { ProjectPayload } from "../types/project";

const projectFormSchema = z.object({
  code: z.string().trim().max(50, "O código deve ter no máximo 50 caracteres"),
  name: z
    .string()
    .trim()
    .min(3, "Informe uma descrição com pelo menos 3 caracteres")
    .max(200, "A descrição deve ter no máximo 200 caracteres"),
  projectTypeId: z.string(),
  city: z
    .string()
    .trim()
    .max(100, "A cidade deve ter no máximo 100 caracteres"),
  state: z.string().trim().max(50, "O estado deve ter no máximo 50 caracteres"),
  notes: z.string().trim(),
});

export type ProjectFormValues = z.infer<typeof projectFormSchema>;

const projectGridBlue = "var(--app-accent-text)";

const projectFormSectionCardSx = {
  background: (theme: {
    palette: {
      info: { main: string };
      primary: { main: string };
    };
  }) =>
    `linear-gradient(135deg, ${alpha(theme.palette.primary.main, 0.07)} 0%, ${alpha(theme.palette.info.main, 0.035)} 100%)`,
  border: "1px solid",
  borderColor: (theme: { palette: { primary: { main: string } } }) =>
    alpha(theme.palette.primary.main, 0.16),
  boxShadow: (theme: { palette: { primary: { main: string } } }) =>
    `0 12px 24px ${alpha(theme.palette.primary.main, 0.07)}`,
  "& .MuiTypography-h5": {
    color: projectGridBlue,
    fontWeight: 800,
  },
  "& .MuiTypography-body2": {
    color: "text.primary",
  },
} as const;

const projectFieldContainerSx = {
  display: "grid",
  gap: 0.75,
  minWidth: 0,
} as const;

const projectFieldLabelSx = {
  color: projectGridBlue,
  fontSize: "0.82rem",
  fontWeight: 700,
  lineHeight: 1.2,
} as const;

type ProjectFieldProps = {
  children: ReactNode;
  label: string;
};

function ProjectField({ children, label }: ProjectFieldProps) {
  return (
    <Box sx={projectFieldContainerSx}>
      <Typography sx={projectFieldLabelSx}>{label}</Typography>
      {children}
    </Box>
  );
}

type ProjectFormProps = {
  initialDataError?: string | null;
  initialValues: ProjectFormValues;
  isCodeAutoGenerated?: boolean;
  isInitialDataLoading?: boolean;
  onCancel: () => void;
  onSubmit: (payload: ProjectPayload) => Promise<void>;
  submitLabel: string;
  subtitle: string;
  title: string;
};

function getSubmitErrorMessage(error: unknown) {
  if (isAxiosError<{ message?: string }>(error)) {
    return error.response?.data?.message ?? "Não foi possível salvar a obra.";
  }

  return "Não foi possível salvar a obra.";
}

function mapFormValuesToPayload(values: ProjectFormValues): ProjectPayload {
  const normalizedProjectTypeId = values.projectTypeId.trim();

  return {
    code: values.code.trim(),
    name: values.name.trim(),
    projectTypeId:
      normalizedProjectTypeId === "" ? null : Number(normalizedProjectTypeId),
    city: values.city.trim(),
    state: values.state.trim(),
    notes: values.notes.trim(),
  };
}

export default function ProjectForm({
  initialDataError = null,
  initialValues,
  isCodeAutoGenerated = false,
  isInitialDataLoading = false,
  onCancel,
  onSubmit,
  submitLabel,
  subtitle,
  title,
}: ProjectFormProps) {
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const projectTypesQuery = useQuery({
    queryKey: ["project-types"],
    queryFn: listProjectTypesRequest,
  });
  const {
    formState: { errors, isSubmitting },
    handleSubmit,
    register,
    watch,
  } = useForm<ProjectFormValues>({
    defaultValues: initialValues,
    resolver: zodResolver(projectFormSchema),
    values: initialValues,
  });
  const currentCode = watch("code").trim();

  const handleCopyCode = async () => {
    if (currentCode === "") {
      return;
    }

    try {
      await navigator.clipboard.writeText(currentCode);
      setSubmitError(null);
      setCopyFeedback("Código da obra copiado.");
    } catch {
      setCopyFeedback(null);
      setSubmitError("Não foi possível copiar o código da obra.");
    }
  };

  const handleFormSubmit = async (values: ProjectFormValues) => {
    try {
      setCopyFeedback(null);
      setSubmitError(null);
      await onSubmit(mapFormValuesToPayload(values));
    } catch (error) {
      setSubmitError(getSubmitErrorMessage(error));
    }
  };

  return (
    <Box sx={{ display: "flex", flexDirection: "column", gap: 3 }}>
      <Box
        sx={{
          background: (theme) =>
            `linear-gradient(135deg, ${alpha(theme.palette.primary.main, 0.08)} 0%, ${alpha(theme.palette.info.main, 0.04)} 100%)`,
          border: "1px solid",
          borderColor: (theme) => alpha(theme.palette.primary.main, 0.18),
          borderRadius: 4,
          boxShadow: (theme) =>
            `0 14px 28px ${alpha(theme.palette.primary.main, 0.08)}`,
          p: { md: 3, xs: 2.5 },
          "& .MuiTypography-h3": {
            color: projectGridBlue,
            fontWeight: 800,
          },
          "& .MuiTypography-body1": {
            color: "text.primary",
            lineHeight: 1.7,
          },
        }}
      >
        <PageHeader
          action={
            <Button
              onClick={onCancel}
              startIcon={<ArrowBackRoundedIcon />}
              sx={{
                borderColor: (theme) => alpha(theme.palette.primary.main, 0.28),
                color: projectGridBlue,
                fontWeight: 700,
              }}
              variant="outlined"
            >
              Voltar
            </Button>
          }
          description={subtitle}
          title={title}
        />
      </Box>

      {isInitialDataLoading ? (
        <SectionCard sx={projectFormSectionCardSx}>
          <Box
            sx={{
              alignItems: "center",
              display: "flex",
              justifyContent: "center",
              minHeight: 240,
            }}
          >
            <CircularProgress />
          </Box>
        </SectionCard>
      ) : null}

      {!isInitialDataLoading ? (
        <Box
          component="form"
          onSubmit={handleSubmit(handleFormSubmit)}
          sx={{ display: "flex", flexDirection: "column", gap: 3 }}
        >
          {initialDataError ? (
            <Alert
              severity="error"
              sx={{
                "& .MuiAlert-message": {
                  fontWeight: 600,
                },
              }}
            >
              {initialDataError}
            </Alert>
          ) : null}
          {copyFeedback ? (
            <Alert
              severity="success"
              sx={{
                "& .MuiAlert-message": {
                  fontWeight: 600,
                },
              }}
            >
              {copyFeedback}
            </Alert>
          ) : null}
          {submitError ? (
            <Alert
              severity="error"
              sx={{
                "& .MuiAlert-message": {
                  fontWeight: 600,
                },
              }}
            >
              {submitError}
            </Alert>
          ) : null}
          {projectTypesQuery.isError ? (
            <Alert
              severity="warning"
              sx={{
                "& .MuiAlert-message": {
                  fontWeight: 600,
                },
              }}
              variant="outlined"
            >
              Não foi possível carregar os tipos de obra. Você ainda pode salvar
              a obra sem esse vínculo.
            </Alert>
          ) : null}

          <SectionCard
            description="Campos principais para identificação e classificação da obra."
            sx={projectFormSectionCardSx}
            title="Dados principais"
          >
            <Box
              sx={{
                display: "grid",
                gap: 2,
                gridTemplateColumns: {
                  lg: "repeat(3, minmax(0, 1fr))",
                  md: "repeat(2, minmax(0, 1fr))",
                  xs: "minmax(0, 1fr)",
                },
              }}
            >
              <ProjectField label="Código">
                <TextField
                  error={Boolean(errors.code)}
                  helperText={
                    errors.code?.message ??
                    (isCodeAutoGenerated
                      ? currentCode === ""
                        ? "O código será gerado automaticamente ao salvar a obra."
                        : "Campo protegido com código gerado automaticamente."
                      : undefined)
                  }
                  placeholder="Ex: OBR-000001"
                  slotProps={{
                    input: {
                      endAdornment:
                        currentCode === "" ? undefined : (
                          <InputAdornment position="end">
                            <Tooltip title="Copiar código">
                              <IconButton
                                aria-label="Copiar código"
                                edge="end"
                                onClick={handleCopyCode}
                                size="small"
                              >
                                <ContentCopyRoundedIcon fontSize="small" />
                              </IconButton>
                            </Tooltip>
                          </InputAdornment>
                        ),
                      readOnly: isCodeAutoGenerated,
                    },
                  }}
                  {...register("code")}
                />
              </ProjectField>
              <ProjectField label="Descrição">
                <TextField
                  error={Boolean(errors.name)}
                  helperText={errors.name?.message}
                  placeholder="Ex: Centro Empresarial Campinas"
                  {...register("name")}
                />
              </ProjectField>
              <ProjectField label="Tipo de obra">
                <TextField
                  error={Boolean(errors.projectTypeId)}
                  helperText={errors.projectTypeId?.message}
                  select
                  {...register("projectTypeId")}
                >
                  <MenuItem value="">Não informado</MenuItem>
                  {(projectTypesQuery.data ?? []).map((item) => (
                    <MenuItem key={item.id} value={String(item.id)}>
                      {item.name}
                    </MenuItem>
                  ))}
                </TextField>
              </ProjectField>
            </Box>
          </SectionCard>

          <SectionCard
            description="Dados de localização para facilitar consultas e vínculo operacional."
            sx={projectFormSectionCardSx}
            title="Localização"
          >
            <Box
              sx={{
                display: "grid",
                gap: 2,
                gridTemplateColumns: {
                  md: "repeat(2, minmax(0, 1fr))",
                  xs: "minmax(0, 1fr)",
                },
              }}
            >
              <ProjectField label="Cidade">
                <TextField
                  error={Boolean(errors.city)}
                  helperText={errors.city?.message}
                  placeholder="Ex: Campinas"
                  {...register("city")}
                />
              </ProjectField>
              <ProjectField label="Estado">
                <TextField
                  error={Boolean(errors.state)}
                  helperText={errors.state?.message}
                  placeholder="Ex: SP"
                  {...register("state")}
                />
              </ProjectField>
            </Box>
          </SectionCard>

          <SectionCard
            description="Informações complementares para consulta futura e contexto da obra."
            sx={projectFormSectionCardSx}
            title="Observações"
          >
            <Box
              sx={{
                display: "grid",
                gap: 2,
              }}
            >
              <ProjectField label="Observações">
                <TextField
                  error={Boolean(errors.notes)}
                  helperText={errors.notes?.message}
                  minRows={4}
                  multiline
                  placeholder="Detalhes adicionais da obra, restrições ou observações operacionais."
                  {...register("notes")}
                />
              </ProjectField>
            </Box>

            <Box
              sx={{
                display: "flex",
                gap: 1.5,
                justifyContent: "flex-end",
                pt: 1,
              }}
            >
              <Button onClick={onCancel} variant="text">
                Cancelar
              </Button>
              <Button
                disabled={isSubmitting || isInitialDataLoading}
                startIcon={<SaveRoundedIcon />}
                type="submit"
                variant="contained"
              >
                {isSubmitting ? "Salvando..." : submitLabel}
              </Button>
            </Box>
          </SectionCard>
        </Box>
      ) : null}
    </Box>
  );
}
